# Generated by Django 3.0.3 on 2020-09-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('mark', models.PositiveSmallIntegerField(choices=[(0, 'неудовлетворительно'), (1, 'удовлетворительно'), (2, 'хорошо'), (3, 'отлично')], verbose_name='Оценка')),
            ],
        ),
    ]
